### ISSUE TITLE
drr.utils.dataset.py is empty

### ISSUE THREAD

**Issue by w6688j** [Epsilon-Lee/DRR-benchmark#1]

**Comment by Epsilon-Lee** [comment]
I am afraid I cannot make it recently since I am involved some other business. And I build this repo for practicing model implementation (only files in the drr/models folder) and I haven't run the code; maybe you can implement the data provider yourself, it's not hard (make sure what specific input format each model require).

**Comment by w6688j** [comment]
Alright, thank you very much!

**Comment by Epsilon-Lee** [comment]
Welcome to contribute ^_^

**Comment by w6688j** [comment]
Hello, what is the data of the input in the RNNAtt17 model? What does N mean, and 256 is splicing directly between arg1 and arg2?
